### PR TITLE
Initial random position and to move down gems and rocks.

### PR DESCRIPTION
**Pull request by machz1988**
Hey guys!

I just added some more attributes and methods to the class Artifact to add functionality to set an initial random position and to move down gems and rocks according a given velocity. Also, I adapted the function move_next in the class Actor, in order to limit the playing area of the player.

I think the only thing is missing is adding functionality to create hit masks according the size of each actor in the game.

### CODE REVIEW

**Review by Sheddycole — APPROVED** [review]
nice!

**Review by Sheddycole — APPROVED** [review]
Superb!

**Review by Sheddycole — APPROVED** [review]

**Review by Sheddycole — APPROVED** [review]

**Review by Sheddycole — APPROVED** [review]

**Review by shanecookofficial — APPROVED** [review]
Looks good!

**Review by Antonio-Saucedo — APPROVED** [review]
This looks good.

**Comment by Giyip** [comment]
Works great

**Pull request merged**
